openapi: 3.0.3
info:
  title: Backend api for the Not Medior Frontend Assessment
  version: 1.0.0
tags:
  - name: Login
  - name: Songs
  - name: Saved
paths:
  /login:
    post:
      tags:
        - Login
      summary: Login
      description: Login to the application. See the request body for the actual credentials you can use to login.
      requestBody:
        description: Login credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
        required: true
      responses:
        '200':
          description:
            Successfully authenticated.
            The auth token is returned in a cookie named `authToken`. You need to include this cookie in subsequent requests either via the `query parameters` or as a `cookie`.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: authToken=abcde12345
        '400':
          description: Credentials are missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingCredentials'
        '401':
          description: Credentials are invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WrongCredentials'
  /songs:
    get:
      tags:
        - Songs
      summary: Get songs
      description: Get songs based on the provided parameters. When no search parameters are provided, all songs will be returned. As this is a large list, this API is really slow.
      parameters:
        - name: name
          in: query
          description: Filter songs on based on name
          required: false
          schema:
            type: string
            example: Goodbye
        - name: artist
          in: query
          description: Filter songs on based on artist
          required: false
          schema:
            type: string
            example: Metallica
        - name: genre
          in: query
          description: Filter songs on based on genre
          required: false
          schema:
            type: string
            example: Rock
        - name: album
          in: query
          description: Filter songs on based on album
          required: false
          schema:
            type: string
            example: Greatest hits
        - name: pageNumber
          in: query
          description: Page number used for pagination. Starts at 1
          required: false
          schema:
            type: string
            example: 1
        - name: amountPerPage
          in: query
          description: Amount of songs per pagination
          required: false
          schema:
            type: string
            example: 10
        - name: authToken
          in: query
          description: authorization token needed to call API
          required: false
          schema:
            type: string
            example: 2aac6c37-4af6-411b-91ee-88e23c02ce66
        - name: authToken
          in: cookie
          description: authorization token needed to call API
          required: false
          schema:
            type: string
            example: 2aac6c37-4af6-411b-91ee-88e23c02ce66
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Songs'
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthorized'
  /saved:
    get:
      tags:
        - Saved
      summary: Get saved songs
      description: Get saved songs based on the provided parameters. When no search parameters parameters are provided, all saved songs will be returned.
      parameters:
        - name: name
          in: query
          description: Filter songs on based on name
          required: false
          schema:
            type: string
            example: Goodbye
        - name: artist
          in: query
          description: Filter songs on based on artist
          required: false
          schema:
            type: string
            example: Metallica
        - name: genre
          in: query
          description: Filter songs on based on genre
          required: false
          schema:
            type: string
            example: Rock
        - name: album
          in: query
          description: Filter songs on based on album
          required: false
          schema:
            type: string
            example: Greatest hits
        - name: pageNumber
          in: query
          description: Page number used for pagination. Starts at 1
          required: false
          schema:
            type: string
            example: 1
        - name: amountPerPage
          in: query
          description: Amount of songs per pagination
          required: false
          schema:
            type: string
            example: 10
        - name: authToken
          in: query
          description: authorization token needed to call API
          required: false
          schema:
            type: string
            example: 2aac6c37-4af6-411b-91ee-88e23c02ce66
        - name: authToken
          in: cookie
          description: authorization token needed to call API
          required: false
          schema:
            type: string
            example: 2aac6c37-4af6-411b-91ee-88e23c02ce66
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Songs'
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthorized'
    post:
      tags:
        - Saved
      summary: Add song to saved
      description: Add songs to your saved playlist by providing the song object in the body.
      requestBody:
        description: Add song to saved playlist
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Song'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddedSong'
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthorized'
    delete:
      tags:
        - Saved
      summary: Delete song from saved
      description: Delete a song from your saved playlist by providing the song's id in a parameter.
      parameters:
        - name: songId
          in: query
          description: ID of the song that needs to be removed from the saved playlist
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemovedSong'
        '400':
          description: Bad request, no songId provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestSaved'
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnAuthorized'

components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          example: test@axxes.com
        password:
          type: string
          example: test
    WrongCredentials:
      type: object
      properties:
        error:
          type: string
          example: Email or password incorrect
    MissingCredentials:
      type: object
      properties:
        error:
          type: string
          example: Credentials are missing
    UnAuthorized:
      type: object
      properties:
        error:
          type: string
          example: You are not authenticated
    AddedSong:
      type: object
      properties:
        message:
          type: string
          example: ADD song
    RemovedSong:
      type: object
      properties:
        message:
          type: string
          example: REMOVE song
    BadRequestSaved:
      type: object
      properties:
        error:
          type: string
          example: no songId provided
    Song:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: 21st Century Breakdown
        artist:
          type: string
          example: Green Day
        year:
          type: integer
          example: 1978
        shortname:
          type: string
          example: 21stcentdigiboy
        bpm:
          type: integer
          example: 150
        duration:
          type: integer
          example: 372025
        genre:
          type: string
          example: rock
        spotifyId:
          type: string
          example: 5H8xFHau0x3PI1CssO6EaX
        album:
          type: string
          example: 21st Century Breakdown
        albumImage:
          type: string
          example: https://i.scdn.co/image/ab67616d0000b273c2ced39899b0d67cd5a724fa
    Songs:
      type: array
      items:
        $ref: '#/components/schemas/Song'
